# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-02 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredient',
            table='ingredients',
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='recipes',
        ),
    ]
